"""remove bone_mass from bodymetric

Revision ID: 3d82d46d29f6
Revises: 559988ce0cb9
Create Date: 2025-11-26 22:36:01.222114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d82d46d29f6'
down_revision: Union[str, Sequence[str], None] = '559988ce0cb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bodymetric', 'bone_mass')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bodymetric', sa.Column('bone_mass', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
