"""add_ffmi_and_bmr

Revision ID: 559988ce0cb9
Revises: 90514b123601
Create Date: 2025-11-26 16:02:19.490987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '559988ce0cb9'
down_revision: Union[str, Sequence[str], None] = '90514b123601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bodymetric', sa.Column('ffmi', sa.Float(), nullable=True))
    op.add_column('bodymetric', sa.Column('bmr', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bodymetric', 'bmr')
    op.drop_column('bodymetric', 'ffmi')
    # ### end Alembic commands ###
