"""Add bone_mass to BodyMetric

Revision ID: 90514b123601
Revises: b456a856eb9f
Create Date: 2025-11-26 15:29:51.044708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90514b123601'
down_revision: Union[str, Sequence[str], None] = 'b456a856eb9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bodymetric', sa.Column('bone_mass', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bodymetric', 'bone_mass')
    # ### end Alembic commands ###
