"""add_user_profile_fields

Revision ID: b456a856eb9f
Revises: 2ebc9f72860b
Create Date: 2025-11-26 14:11:17.170887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b456a856eb9f'
down_revision: Union[str, Sequence[str], None] = '2ebc9f72860b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('sex', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('height', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'height')
    op.drop_column('user', 'sex')
    op.drop_column('user', 'birth_date')
    # ### end Alembic commands ###
